base_dir = "actis"
data = "Flywing"
checkpoint_path = "./experiments/myexperiment/train/checkpoints/best_model.pth"
experiment = "myexperiment"
num_annotated = 19
batch_size_labeled = 4
batch_size_unlabeled = 8
num_workers = 0
training_steps = 50000
in_channels = 1
num_fmaps = 32
fmap_inc_factors = 2
downsample_factors = [ [ 2, 2,], [ 2, 2,], [ 2, 2,], [ 2, 2,],]
num_fmaps_out = 3
constant_upsample = false
padding = "same"
activation = "ReLU"
learning_rate = 0.01
seed = 1
semi_loss_weight = 1.0
quantile = 0.2
quantile_end = 0.1
quantile_warmup_steps = 5000
load_student_weights = true
warmup_steps = 0
fast_update_slow_model = false
size = 128
encoder_weights = "imagenet"
no_moco = false
s = 1.0
