base_dir = "C:/Users/lorenz/OneDrive - Charité - Universitätsmedizin Berlin/semi_supervised_IS"
#base_dir = "/fast/AG_Kainmueller/jrumber/PhD/semi_supervised_IS"
data = "data/DSB2018_n0/train/train_data.npz"
#data = "data/Mouse_n0/train/train_data.npz"
#data = "data/Flywing_n0/train/train_data.npz"

checkpoint_path = "C:/Users/lorenz/OneDrive - Charité - Universitätsmedizin Berlin/semi_supervised_IS/experiments/dsb_seed1_samples19/train/checkpoints/best_model.pth"
experiment = "dsb_seed1_samples19_semi"
num_annotated = 19
batch_size_labeled = 4
batch_size_unlabeled = 8
num_workers = 4
training_steps = 50000
in_channels = 1
num_fmaps = 32
fmap_inc_factors = 2
downsample_factors = [ [ 2, 2,], [ 2, 2,], [ 2, 2,], [ 2, 2,],]
num_fmaps_out = 3
constant_upsample = false
padding = "same"
activation = "ReLU"
learning_rate = 0.01
seed = 1
semi_loss_weight = 1.0
quantile = 0.2
quantile_end = 0.1
quantile_warmup_steps = 5000
load_student_weights = true
warmup_steps = 0
fast_update_slow_model = false
s = 1.0
size = 128