# This workflow will install Python dependencies and run the implemented unittests

name: ci-python-unitest

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

permissions:
  contents: read

jobs:
  build_linux:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install_linux
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Running_linux
        run: |
          actis -h

  test_integration:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: test_linux
        run: |
          pip install -U pytest
          pip install -e .
          pytest test/test_integration.py
